// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBohsuMW3GtFTKEkGGperffJJ9a7qYZW5Y',
    appId: '1:960695291934:web:6ca7184dc6e29f3b06de0f',
    messagingSenderId: '960695291934',
    projectId: 'common-sense-cbff2',
    authDomain: 'common-sense-cbff2.firebaseapp.com',
    storageBucket: 'common-sense-cbff2.appspot.com',
    measurementId: 'G-YGLFM6RFTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEoHHxOIy8pRDnaBheLVViv81QuQr9ZZI',
    appId: '1:960695291934:android:3d02c42ade8341f206de0f',
    messagingSenderId: '960695291934',
    projectId: 'common-sense-cbff2',
    storageBucket: 'common-sense-cbff2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArnF-eXCEo5SzXHgPNIsazHS072UlxJCc',
    appId: '1:960695291934:ios:9eeed456d367a11406de0f',
    messagingSenderId: '960695291934',
    projectId: 'common-sense-cbff2',
    storageBucket: 'common-sense-cbff2.appspot.com',
    iosBundleId: 'com.example.commonSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArnF-eXCEo5SzXHgPNIsazHS072UlxJCc',
    appId: '1:960695291934:ios:4ac23c132b84973006de0f',
    messagingSenderId: '960695291934',
    projectId: 'common-sense-cbff2',
    storageBucket: 'common-sense-cbff2.appspot.com',
    iosBundleId: 'com.example.commonSense.RunnerTests',
  );
}
